name: Node.js Setup on Ubuntu and Windows - Cache

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04, windows-2019, windows-2022, windows-2025]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            # For Windows, also include appdata folder
            C:\Users\runneradmin\AppData\Roaming\npm-cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
