name: Node.js Setup on Windows

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-22.04  # Change to Windows runner
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        
      - name: Install dependencies
        run: npm -version
        shell: pwsh  # PowerShell is the default shell on Windows runners
        
